Repository NASA-AMMOS/aerie-cli, pull requests merged in 2023-07, with the labels that each got.

#26 Client Method Changes for Deploying Scheduling Goals/Activity Presets
  src/aerie_cli/aerie_client.py
  src/aerie_cli/commands/scheduling.py
Labels: enhancement, breaking change

#44 Update Expansion Query
  src/aerie_cli/aerie_client.py
  src/aerie_cli/commands/expansion.py
Labels: update

#57 Hotfix: Windows Paths
  pyproject.toml
  src/aerie_cli/persistent.py
Labels: bug

#59 Hotfix: Windows Paths
  pyproject.toml
  src/aerie_cli/persistent.py
Labels: bug

#11 Support Activity Anchoring + Refactoring/Improvements
  .github/workflows/test.yml
  src/aerie_cli/aerie_client.py
  src/aerie_cli/schemas/api.py
  src/aerie_cli/schemas/client.py
  src/aerie_cli/utils/serialization.py
  tests/unit_tests/files/expected_results/get_activity_plan_by_id.json
  tests/unit_tests/files/inputs/create_activity_plan_1.json
  tests/unit_tests/files/inputs/create_activity_plan_2.json
  tests/unit_tests/files/inputs/get_activity_start_time.json
  tests/unit_tests/files/mock_responses/create_activity.json
  tests/unit_tests/files/mock_responses/create_activity_plan_1.json
  tests/unit_tests/files/mock_responses/create_activity_plan_2.json
  tests/unit_tests/files/mock_responses/get_activity_plan_by_id.json
  tests/unit_tests/files/mock_responses/update_activity.json
  tests/unit_tests/test_aerie_client.py
  tests/unit_tests/test_dataclasses.py
  tests/unit_tests/test_utils.py
Labels: enhancement, breaking change
